@startuml classDiagram

class Utente {
-userId: int
-username: String
-password: String
-name: String
-surname: String
-email: String
-phone: String
+getUserDetails(): String
}


class Prodotto {
-productId: int
-name: String
-description: String
-price: double
-nameObj: String
-image: String
+getProductDetails(): String
}

class Carello {
-cartId: int
-items: List +addItem(product: Product)
+removeItem(product: Product)
+getTotalPrice(): double
}

class Ordine {
-orderId: int
-user: User
-products: List -totalPrice: double
+confirmOrder()
+cancelOrder()
}

class Pagamento {
-paymentId: int
-orderId: int
-amount: double
-paymentStatus: String
+processPayment(): boolean
}

Utente -- Carello
Carello -- Prodotto
Utente -- Ordine
Ordine -- Prodotto
Ordine -- Pagamento

@enduml