@startuml useCase
left to right direction

actor User as U

rectangle "Login / Registrazione" {
U --> (Effettuare il login)
U --> (Effettuare la registrazione)
}

rectangle "Movimento" {
U --> (Muoversi all'interno dell'ambiente virtuale)
}

rectangle "Visionare il prodotto" {
U --> (Visualizzare i prodotti disponibili nel negozio)
}

rectangle "Aggiungere al carrello" {
U --> (Aggiungere un prodotto al carrello virtuale)
}

rectangle "Acquistare" {
U --> (Completare l'acquisto dei prodotti presenti nel carrello)
}

@enduml